.gitignore
package-lock.json
package.json
src/services/templateService.js
src/templates/components/componentJsTemplate.js
src/templates/components/componentTestTestingLibraryTemplate.js

Updates:
- Use camelCased component name for selecting component in `@testing-library` test file (#3)
- Use `getByTestId` vs `getByText` by default in `@testing-library` test file (#4)

Close #3 and #4

---

src/templates/components/componentLazyTemplate.js

Use `null` instead of a `<Fragment />` as an empty fallback.

Remove unnecessary use of Fragment in Lazy template

---

CHANGELOG.md
package-lock.json
package.json
readme.md
src/services/componentTemplateService.js

This feature will allow for creating custom templates that Generate React CLI can use
instead of the built-in templates that come with it.
Closes #12

Feature: Custom Templates

---

.github/workflows/nodejs.yml
readme.md
src/cli.js
src/services/grcConfigService.js

GRC is now more configurable by allowing the developer to extend the
**generate-react-cli.json** config file and allowing them to add an additional custom component
commands dynamically.
Closes #14

Custom Component Commands

---

package-lock.json
package.json
readme.md
src/actions/componentActions.js
src/cli.js
src/services/componentTemplateService.js
src/services/grcConfigService.js

- The `component` command now has a new `type` option. This new `type` option will replace the custom component commands. Meaning you now pass the custom component as type option (e.g `npx generate-react-cli component HomePage --type=page` ) that you
have configured in your GRC config file.
- update dependencies
- update readme

feat: 🎸 Add a new "type" option to the component command

---

src/templates/component/componentTestTestingLibraryTemplate.js

- Don't use `cleanup` ([link](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-cleanup))
- Use `screen` instead of destructuring `render` ([link](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-cleanup))
Note: This is not a breaking change for our @britannica `renderWithApolloProvider`, `renderWithRouter`, and `renderWithRouterAndApolloProvider` test utilities.

@testing-library recommendations from Kent

---

src/actions/componentActions.js

Currently you can name your components all lowercase and GRC will comply and generate the component as requested, according to the best practices, custom components must start with a upper case letter.
I think this package should enforce components to start with a upper case letter, as pointed by [the React team and JSX docs](https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized)  and of course [StackOverflow](https://stackoverflow.com/questions/30373343/reactjs-component-names-must-begin-with-capital-letters). 
This PR does just that, uses lodash's `upperFirst` and enforces the rule to the folder, file name and component name.

React components must start with a upper case letter.

---

src/cli.js

Allow users to create multiple components with a single command. Options will be applied to all components.
**Example**
```js
npx generate-react-cli component ComponentA ComponentB ComponentC --withLazy=true
```
The above command will create three components, all with the `withLazy` flag set to true.

feat: allow generation of multiple components at once

---

readme.md
src/templates/component/componentTsTemplate.js
src/utils/generateComponentUtils.js

Added the possibility to use `templateName` to replace the given component name as camelCase in custom templates.
Updated the Readme to reflect this.
--> This would close issue #43 
Changed the default TypeScript template to not use `React.FC` anymore, since its not recommended anymore.

Camel case replacement

---

src/templates/component/componentStoryTemplate.js

Storybook team is advising developers to migrate away from storiesOf API, as per this doc: https://github.com/storybookjs/storybook/blob/next/lib/core/docs/storiesOf.md. 
This commit upgrades the stories template to this modern syntax.

refactor(story): update to modern storybook syntax

---

readme.md
src/commands/generateComponent.js
src/utils/generateComponentUtils.js

@arminbro this changes adds support for a `--dry-run` flag. This allows you to preview the paths of the files which are generated before actually writing the files.  By default the flag is false.
Sample execution:
```
❯ npx generate-react-cli component Foo --dry-run
Foo.tsx was successfully created at src/components/Foo/Foo.tsx
Foo.module.css was successfully created at src/components/Foo/Foo.module.css
Foo.test.tsx was successfully created at src/components/Foo/Foo.test.tsx
Foo.stories.tsx was successfully created at src/components/Foo/Foo.stories.tsx
Foo.lazy.tsx was successfully created at src/components/Foo/Foo.lazy.tsx
NOTE: The "dry-run" flag means no changes were made.
```
Let me know if you have any questions. Thanks for considering this pull request.

feat: adds dry-run flag to preview generated paths without writing files

---

.github/workflows/publish.yml

- syntax spacing adjustment for npm token & gh token

fix: gh publish action

---

readme.md
src/utils/generateComponentUtils.js

Hey, I would like to use `generate-react-cli` for creating redux action types files, like this one:
```js
// src/redux/actionTypes.js
export const GET_TEMPLATE_NAME_REQUEST = 'GET_TEMPLATE_NAME_REQUEST';
export const GET_TEMPLATE_NAME_SUCCESS = 'GET_TEMPLATE_NAME_SUCCESS';
export const GET_TEMPLATE_NAME_FAILURE = 'GET_TEMPLATE_NAME_FAILURE';
```
This PR adds possibility to do so.

feat: Adds support for uppercase snake case TEMPLATE_NAME

---

readme.md
src/commands/generateComponent.js
src/utils/generateComponentUtils.js

**Updates:** 
- Support any component filename format
**Fixes issues:**
- https://github.com/arminbro/generate-react-cli/issues/54
- https://github.com/arminbro/generate-react-cli/issues/65
> Please note the `TemplateName` keyword in the template filename. GRC will use this keyword and replace it with your component name (in whichever format you typed the component name in the command) as the filename.

feat: Support any component filename format

---

readme.md
src/commands/generateComponent.js
src/utils/generateComponentUtils.js

Added an extra option `-f` or `--flat` to create the files in the same folder without creating new folder in the name of the component.
This will fix the feature request of #64

fix-#64 - Add option to avoid new folder

---

bin/generate-react.js
package-lock.json
package.json
src/cli.js
src/cli.test.js
src/commands/generateComponent.js
src/templates/component/componentCssTemplate.js
src/templates/component/componentJsTemplate.js
src/templates/component/componentLazyTemplate.js
src/templates/component/componentStoryTemplate.js
src/templates/component/componentTestDefaultTemplate.js
src/templates/component/componentTestEnzymeTemplate.js
src/templates/component/componentTestTestingLibraryTemplate.js
src/templates/component/componentTsLazyTemplate.js
src/templates/component/componentTsTemplate.js
src/utils/generateComponentUtils.js
src/utils/grcConfigUtils.js

Note:
- Please note with these new npm dependency updates, GRC has switched over to using the new Node.js [ECMAScript module system](https://nodejs.org/docs/latest/api/esm.html) instead of the older [CommonJs](https://nodejs.org/docs/latest/api/modules.html) module system. This update helps us keep our dependency up to date, which also now uses the new ECMAScript module system.
This PR fixes #72 and updates other dependencies as well.

Npm Dependency Updates

---

src/commands/generateComponent.js
src/utils/generateComponentUtils.js

I've added an OR check to see if the `flat` property is specified within the `.JSON` file as well as the existing command. This is helpful so you don't have to remember to add it to commands and it can be abstracted away from the command line.
My main use for this is when generating either hooks or slices, having flat pre-defined within the JSON file just makes my life a smidge easier. Thanks for the package though as I use it so often and this would just be the icing on top 🍰
Example:

feat: Allow Flat Property within JSON

---

src/templates/component/componentStyledTemplate.js
src/utils/generateComponentUtils.js
src/utils/grcConfigUtils.js

Adds an option to use [styled-components](https://styled-components.com/) instead of CSS modules. 
During setup:
- Ask user "Does this project use styled-components?"
- If the answer is yes, skip "Does this project use CSS modules?" and "Does this project use a CSS Preprocessor?" 
During component creation: 
- Use the existing `withStyle` setting to determine whether to generate a styled component in this instance
- If `withStyle` is true:
- the `div` in the template is replaced by a `ComponentNameWrapper`, and 
- a corresponding `ComponentName.styled.{js,ts}` file is created, defining `ComponentNameWrapper` as a `div`.
Could close #48.

feat: styled-components support

---

src/utils/generateComponentUtils.js

File names like template-name, template_name etc. are working fine

Fix an issue with the type of case in the custom file names

---

readme.md
src/templates/component/componentCssTemplate.js
src/templates/component/componentJsTemplate.js
src/templates/component/componentLazyTemplate.js
src/templates/component/componentStoryTemplate.js
src/templates/component/componentStyledTemplate.js
src/templates/component/componentTestDefaultTemplate.js
src/templates/component/componentTestEnzymeTemplate.js
src/templates/component/componentTestTestingLibraryTemplate.js
src/templates/component/componentTsLazyTemplate.js
src/templates/component/componentTsTemplate.js

This PR updates the GRC default templates to use the `templatename` casing instead of `TemplateName`. This change ensures the format matches how users type it in their command prompt.
I believe this should be the default behavior, regardless of React's PascalCase convention for component names.
Closes #81

fix: the default grc templates to use `templatename` casing

---

.github/workflows/publish.yml
.gitignore
package-lock.json
package.json
readme.md
src/commands/generateComponent.js

- Removed OpenAI/AI-powered component description features (`--describe` flag)
- Fixed Commander v14 compatibility by removing invalid short flag format (`-dr` -> `--dry-run` only)
- Updated dependencies (semantic-release, commitlint, prettier, chalk, eslint-plugin-prettier)
- **REMOVED**: `--describe` flag and AI-powered component generation features
- **CHANGED**: `-dr` short flag no longer supported, use `--dry-run` instead
- Simplified the CLI by removing unused AI integration
- Fixed compatibility issues with Commander.js v14, which doesn't support multi-character short flags
- Updated dependencies to the latest versions for security and performance

fix: remove AI features and fix Commander v14 compatibility
